- src/app/features/impact-analysis/impact-analysis-visualisation/impact-analysis-visualisation.component.ts
- src/app/features/impact-analysis/impact-analysis-visualisation/impact-nodes-list/impact-nodes-list.component.ts
- src/app/features/impact-analysis/impact-analysis-visualisation/impact-warnings/impact-warnings.component.ts
- src/app/features/impact-analysis/impact-analysis-visualisation/models/impact-analysis-model.ts
- src/app/features/impact-analysis/impact-analysis.component.html
- src/app/features/impact-analysis/impact-analysis.component.scss
- src/app/features/impact-analysis/impact-analysis.component.ts
- Ability to select/unselect multiple modules
- Display impact analysis for each selected module
- Clustering adjusted to work with multiple modules
- Clustering list no longer contains main modules and duplicates
> Multiple modules displaying

- src/app/features/private/private.component.html
- src/app/features/private/private.component.scss
- src/app/features/private/private.component.ts
- src/app/features/private/private.module.ts
- src/app/features/private/private.service.ts
- src/app/features/statistics/yang-stats.component.ts
- src/app/features/yang-module-details/yang-module-details.component.html
- src/app/features/yang-search/yang-search.component.html
- src/app/features/yang-tree/yang-tree.component.html
- src/app/features/yang-tree/yang-tree.component.scss
- src/app/features/yang-validator/yang-validator.component.html
- src/app/shared/ag-grid/app-ag-grid.component.css
> Private-page statistics tables position fixed

- src/app/features/private/private.component.html
- src/app/features/private/private.component.ts
- src/app/features/yang-search/yang-search.component.ts
> Redundant scroll bars removed

- src/app/features/yang-validator/yang-validator.component.html
- src/app/features/yang-validator/yang-validator.component.ts
- src/app/features/yang-validator/yang-validator.service.ts
> Display validators version in YANG Validator page

- src/app/core/data.service.ts
- src/app/features/yang-module-details/yang-module-details.component.html
- src/app/features/yang-module-details/yang-module-details.component.ts
- src/app/features/yang-module-details/yang-module-details.module.ts
- src/app/features/yang-module-details/yang-module-details.service.ts
> Field validator fixed for module details

- src/app/features/account/account/account.component.html
- src/app/features/account/account/account.component.scss
- src/app/features/account/account/account.component.ts
- src/app/features/account/account/account.service.ts
> Add motivation field to the registration form

- src/app/features/impact-analysis/impact-analysis.component.html
- src/app/features/impact-analysis/impact-analysis.component.ts
- If user did not selected module name from list and clicked on button
application looked like someting is being fetched from backend.
- However, it was only wrong condition for loader icon
This resolves #27
> Bugfix: Loader spinning even if nothing is being fetch from backend

- src/app/features/yang-validator/validation-result/validation-result.component.html
- src/app/features/yang-validator/yang-validator.component.ts
- src/app/features/yang-validator/yang-validator.service.ts
- Only one output was displayed, but there are two - stdout and stderr
- Conditions added to display those results which are not empty strings
> Bugfix: Display output of validation correctly

- src/app/features/static-content/contribute/contribute.component.html
- src/app/features/static-content/query/query.component.html
- src/app/features/static-content/query/query.component.ts
- src/app/features/static-content/static-content-routing.module.ts
- src/app/features/static-content/static-content.module.ts
- src/app/features/static-content/use/use.component.html
- src/index.html
- new tab added: Query
- Use tab renamed to Use cases
- Postman collection download Info moved from Contribute to Query tab
- Description of yang-catalog node moved from Use cases to Query tab
> Query tab added to the navigation menu

- package-lock.json
- package.json
- src/app/features/account/account.module.ts
- src/app/features/account/account/account.component.html
- src/app/features/account/account/account.component.ts
- src/environments/environment.prod.ts
- src/environments/environment.ts
> reCAPTCHA validation added to the registration form

- src/app/features/account/account/account.component.html
- src/app/features/account/account/account.component.ts
- src/app/features/account/account/account.service.ts
> Various updates to the registration form

- src/app/features/account/account/account.component.ts
- src/app/features/account/account/account.service.ts
- src/environments/environment.prod.ts
- src/environments/environment.ts
> Changed endpoint which checks whether username already in use

- src/app/features/yang-validator/yang-validator.component.html
- src/app/features/yang-validator/yang-validator.component.ts
> Query parameters added for YANG Validator

- src/app/features/yang-validator/api-overview/api-overview.component.html
- src/app/features/yang-validator/api-overview/api-overview.component.ts
- src/app/features/yang-validator/yang-validator.component.html
- src/app/features/yang-validator/yang-validator.component.ts
- src/app/features/yang-validator/yang-validator.module.ts
- Text and examples updates
- Moved into separate component
> Move YANG Catalog API overview into separate component

- src/app/features/yang-module-details/yang-module-details.component.html
- src/app/features/yang-module-details/yang-module-details.component.ts
> Bugfix: Deviations list display fixed

- src/index.html
> Matomo code snippet added into index.html

- src/index.html
> Add link headers to enable images preloading

- src/index.html
- src/scss/yc.scss
> Fixed formatting of newlines at private-page tables

- src/app/app-routing.module.ts
- src/app/app.component.ts
- src/app/features/static-content/static-content-routing.module.ts
- src/index.html
> Setting different titles for individual pages

- src/index.html
> Use preloading for fonts

- src/index.html
> Add HTTPS to the Matomo server URL

- src/app/features/static-content/use/use.component.html
- src/index.html
> Images loading strategy moved into NGINX config file

- src/app/features/yang-tree/yang-tree.component.ts
- src/app/features/yang-tree/yang-tree.service.ts
- src/proxy.conf.json
> Bugfix: Crete correct request for YANG Tree if revision not provided

- src/app/features/private/private.component.ts
- src/app/features/yang-validator/api-overview/api-overview.component.html
> Update headers after pyang 2.5.3 update

- src/app/features/static-content/static-content-routing.module.ts
- src/app/features/static-content/static-content.component.ts
- src/app/features/static-content/static-content.module.ts
> Redirect to home component correctly

- src/app/features/private/private.component.ts
- src/app/features/private/private.service.ts
- src/app/features/yang-validator/api-overview/api-overview.component.html
> Update headers after yanglint v2.0.194 update

- src/app/features/private/private.component.ts
> Bugfix: AllYANGPageMain table columns fixed

- src/app/app.module.ts
- src/app/features/private/private.component.html
- src/app/features/private/private.component.ts
> Query params added for tabs in YANG Modules Stats

- src/app/features/private/private.component.html
- src/app/features/private/private.component.ts
> ETSI navigation tab added

- src/app/features/private/private.component.ts
- src/app/features/private/private.service.ts
> Fetching data from api/problematic-drafts endpoint

- src/app/features/impact-analysis/impact-analysis-visualisation/models/impact-analysis-model.ts
- src/app/features/impact-analysis/impact-analysis-visualisation/node-context-menu/node-context-menu.component.html
- src/app/features/impact-analysis/impact-analysis.component.ts
- src/app/features/impact-analysis/impact-analysis.service.ts
- src/app/features/yang-module-details/yang-module-details.component.html
- src/app/features/yang-search/yang-search.component.html
- src/app/features/yang-tree/yang-tree.component.html
> Display warning if module does not exist

- src/app/features/yang-validator/yang-validator-routing.module.ts
- src/app/features/yang-validator/yang-validator.component.ts
> fix: yangvalidator API docs component displaying

- src/app/features/yang-validator/api-overview/api-overview.component.html
- src/app/features/yang-validator/api-overview/api-overview.component.ts
> docs: added link to the swagger documentation

- src/app/features/private/private.component.ts
- src/app/features/yang-validator/api-overview/api-overview.component.html
> chore: update headers after yanglint v2.0.231 update

- src/app/core/yc-validations.service.ts
- src/app/features/yang-search/yang-search.component.html
- src/app/features/yang-search/yang-search.component.ts
- src/app/features/yang-validator/api-overview/api-overview.component.ts
This resolves #97 
- check whether regex expression is actually valid before sending
request to the backend
> fix: check if regex is valid is using regex search
